### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by elefps** [LLNL/fpzip#4]
Dear writers,

I have a question on the algorythm . what kind of lossless techique (ie entropy, dictionary type) is fzip? 

Thanks in advance!
Best regards,
EP

**Comment by lindstro** [comment]
fpzip uses [range coding](https://en.wikipedia.org/wiki/Range_encoding) (a type of entropy code) of the sign and number of significant bits of residuals (prediction errors).  Any remaining bits, such as the value bits of the residuals, are passed through verbatim.  The algorithm is described in [this paper](https://doi.org/10.1109/TVCG.2006.143).

**Comment by elefps** [comment]
thank you for your answer! I am thinking of adding fzip to my point cloud compression codec, therefore i will leave this issue open in case i have more questions.  Is there anything specific i should pay attention to?

**Comment by lindstro** [comment]
fpzip is not likely to work well at all on point clouds.  It was designed for 2D and 3D structured scalar fields that exhibit spatial correlations in all dimensions (see the [README](https://github.com/LLNL/fpzip/blob/develop/README.md) file).  Point clouds are not correlated in even a single dimension, which makes them difficult to compress.

There are better compressors that have been designed for point clouds.  We've done some recent work on lossy point cloud compression that is currently in review.  I'd be happy to share a preprint at a future date.

**Comment by elefps** [comment]
I'd be very interested in the preprint when its ready, as i am actively researching for new point cloud compression methods.

As for fzip, i used it on a tranformed space where point cloud points are kinda correlated .  the reconstruction was indeed lossless so I suppose it worked? I was in search for  a more efficient compressor to replace arithmetic coding that took place at the end of my pipeline

**Comment by lindstro** [comment]
Not a big deal, but the compressor is called fpzip (fp = floating point). :-)

I'm assuming you're compressing each spatial coordinate separately as a 1D array.  In this case, fpzip will compress the difference between two consecutive values, which likely share at least sign and exponent, so you should see some compression.  You can tell fpzip to use less than full precision if you don't need fully lossless compression.
