### ISSUE TITLE
fpzip no longer supported in python3.11

### ISSUE THREAD

**Issue by Bootstrap360** [LLNL/fpzip#7]
fpzip is not supported by Python3.11

**Comment by lindstro** [comment]
Looks like there are no fpzip wheels for 3.11.  @william-silversmith, would you like to comment?

**Comment by william-silversmith** [comment]
Hi all! I updated the build system and released cPython 3.11 wheels just now.

**Comment by lindstro** [comment]
Thanks @william-silversmith!
